#!/usr/bin/env node
// build.mjs — Merge models.json (objective) + routing.json (subjective)
// into model-map.json, a single self-contained artifact for consumers who
// prefer one fetch. Generated; do not hand-edit.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "model-map.json");

const load = async (n) => JSON.parse(await readFile(join(ROOT, n), "utf8"));

async function main() {
  const models = await load("models.json");
  const routing = await load("routing.json");

  const merged = {
    $note:
      "Generated by tools/build.mjs — merge of models.json (objective, synced from models.dev MIT) + routing.json (subjective, hand-maintained). Do NOT hand-edit. Edit routing.json; run sync.mjs for objective data.",
    version: routing.version,
    updated: routing.updated,
    review_due: routing.review_due,
    synced_at: models.synced_at,
    objective: {
      $source: models.$source,
      providers_of_interest: models.providers_of_interest,
      model_count: models.model_count,
      models: models.models,
    },
    subjective: {
      redline_models: routing.redline_models,
      cross_provider_review: routing.cross_provider_review,
      provider_picks: routing.provider_picks,
      task_types: routing.task_types,
      mcp: routing.mcp,
      consumption_contract: routing.consumption_contract,
    },
  };

  await writeFile(OUT, JSON.stringify(merged, null, 2) + "\n");
  console.log(`[ok] wrote ${OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
